### PR TITLE
Fix Fever API

### PR DESCRIPTION
**Pull request by ThinkChaos**

### CODE REVIEW

**Comment by ThinkChaos** [comment]
I believe this is now feature complete. I'll make another PR if I find anything else that's missing/buggy.

**Comment by ThinkChaos** [comment]
#24 should be fine to close after this is merged 😃

**Comment by ThinkChaos** [comment]
I removed the docker commit from this PR.

**Comment by pietheinstrengholt** [comment]
Thanks again!

**Pull request merged**
